const $ = (selector) => document.querySelector(selector);
const audio = $('#audio');
const savedLibraryFolders=(()=>{try{const folders=JSON.parse(localStorage.getItem('nightwave-library-folders')||'[]');return Array.isArray(folders)?folders.filter(folder=>typeof folder==='string'&&folder):[]}catch{return []}})();
let db, state = { tracks: [], playlists: [], selected: 'all', currentId: null, shuffle: false, repeat: false, objectUrl: null, query: '', sort: { key: 'artist', direction: 'asc' }, selectedTrackIds: new Set(), selectionAnchor: null, libraryFolders: savedLibraryFolders };
const metadataParser = import('./vendor/music-metadata.bundle.mjs').then(module=>module.parseBlob).catch(()=>null);
const sidebarMin=265,sidebarMax=415,savedSidebarWidth=Number(localStorage.getItem('nightwave-sidebar-width'));if(savedSidebarWidth>=sidebarMin&&savedSidebarWidth<=sidebarMax)document.documentElement.style.setProperty('--sidebar-width',`${savedSidebarWidth}px`);

function openDB() { return new Promise((resolve, reject) => { const req = indexedDB.open('nightwave-player', 1); req.onupgradeneeded = () => { const d=req.result; d.createObjectStore('tracks',{keyPath:'id'}); d.createObjectStore('playlists',{keyPath:'id'}); }; req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); }
function all(store) { return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}); }
function put(store, value) { return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=resolve;r.onerror=()=>reject(r.error)}); }
function del(store, key) { return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(key);r.onsuccess=resolve;r.onerror=()=>reject(r.error)}); }
const id = () => crypto.randomUUID();
const time = seconds => { if(!Number.isFinite(seconds)) return '—'; const m=Math.floor(seconds/60),s=Math.floor(seconds%60); return `${m}:${String(s).padStart(2,'0')}`; };
const fileTitle = name => name.replace(/\.[^.]+$/,'').replace(/[_.-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const decodeText = bytes => new TextDecoder('utf-8').decode(bytes).replace(/\0/g,'').trim();
const read32 = (bytes, offset) => ((bytes[offset]<<24)|(bytes[offset+1]<<16)|(bytes[offset+2]<<8)|bytes[offset+3])>>>0;
const readLE32 = (bytes, offset) => (bytes[offset]|(bytes[offset+1]<<8)|(bytes[offset+2]<<16)|(bytes[offset+3]<<24))>>>0;
function parseCommentBlock(bytes,start=0){const result={};let offset=start;const vendor=readLE32(bytes,offset);offset+=4+vendor;const count=readLE32(bytes,offset);offset+=4;for(let i=0;i<count&&offset+4<=bytes.length;i++){const length=readLE32(bytes,offset);offset+=4;const [key,...value]=decodeText(bytes.subarray(offset,offset+length)).split('=');offset+=length;if(key&&value.length)result[key.toLowerCase()]=value.join('=')}return result}
function parseId3(bytes){if(decodeText(bytes.subarray(0,3))!=='ID3')return {};const version=bytes[3],limit=10+((bytes[6]<<21)|(bytes[7]<<14)|(bytes[8]<<7)|bytes[9]),result={},isV22=version===2,headerSize=isV22?6:10;let offset=10;while(offset+headerSize<=limit&&offset+headerSize<=bytes.length){const id=decodeText(bytes.subarray(offset,offset+(isV22?3:4)));const size=isV22?((bytes[offset+3]<<16)|(bytes[offset+4]<<8)|bytes[offset+5]):version===4?((bytes[offset+4]<<21)|(bytes[offset+5]<<14)|(bytes[offset+6]<<7)|bytes[offset+7]):read32(bytes,offset+4);if(!id||!size)break;const value=bytes.subarray(offset+headerSize,Math.min(offset+headerSize+size,bytes.length));const encoding=value[0];const text=(encoding===1||encoding===2?new TextDecoder('utf-16').decode(value.subarray(1)):decodeText(value.subarray(1))).replace(/\0/g,'').trim();if(id==='TIT2'||id==='TT2')result.title=text;if(id==='TPE1'||id==='TP1')result.artist=text;if(id==='TALB'||id==='TAL')result.album=text;offset+=headerSize+size}return result}
function parseFlac(bytes){if(decodeText(bytes.subarray(0,4))!=='fLaC')return {};let offset=4;while(offset+4<=bytes.length){const header=bytes[offset],type=header&127,length=(bytes[offset+1]<<16)|(bytes[offset+2]<<8)|bytes[offset+3];if(type===4){const tags=parseCommentBlock(bytes,offset+4);return {title:tags.title,artist:tags.artist,album:tags.album}}offset+=4+length;if(header&128)break}return {}}
function parseMp4(bytes){const result={},wanted={'©nam':'title','©ART':'artist','aART':'artist','©alb':'album'},containers=new Set(['moov','udta','meta','ilst']);function walk(start,end,parent=''){let offset=start;while(offset+8<=end){let size=read32(bytes,offset),header=8;if(size===1&&offset+16<=end){size=read32(bytes,offset+8);header=16}if(!size||offset+size>end)break;const type=String.fromCharCode(bytes[offset+4],bytes[offset+5],bytes[offset+6],bytes[offset+7]);const content=offset+header;if(type==='data'&&wanted[parent]&&content+8<=offset+size){const value=decodeText(bytes.subarray(content+8,offset+size));if(value&&!result[wanted[parent]])result[wanted[parent]]=value}else if(containers.has(type)||wanted[type])walk(content+(type==='meta'?4:0),offset+size,type);offset+=size}}walk(0,bytes.length);return result}
async function embeddedTags(file){const bytes=new Uint8Array(await file.arrayBuffer());const tags={...parseId3(bytes),...parseFlac(bytes),...parseMp4(bytes)};if(!tags.title&&!tags.artist&&!tags.album){const text=decodeText(bytes);const marker=text.indexOf('vorbis');if(marker>=0){const comments=parseCommentBlock(bytes,marker+6);tags.title=comments.title;tags.artist=comments.artist;tags.album=comments.album}}return tags}
async function trackMetadata(file){ const fallback=fileTitle(file.name).split(' - '); const defaults={title:fallback.length>1?fallback.slice(1).join(' - '):fileTitle(file.name),artist:fallback.length>1?fallback[0]:'Unknown artist',album:'Local files'}; try { const tags=await embeddedTags(file);return {...defaults,title:tags.title?.trim()||defaults.title,artist:tags.artist?.trim()||defaults.artist,album:tags.album?.trim()||defaults.album}; } catch { const parseBlob=await metadataParser;if(!parseBlob)return defaults;try{const metadata=await parseBlob(file,{skipCovers:true}),tags=metadata.common;return {...defaults,title:tags.title?.trim()||defaults.title,artist:tags.artist?.trim()||defaults.artist,album:tags.album?.trim()||defaults.album}}catch{return defaults} } }
// Playlist memberships use a file key rather than the library's temporary track ID.
// That lets a playlist survive when its tracks are unloaded and later loaded again.
const playlistTrackKeys = playlist => playlist.trackKeys || [];
function visibleTracks(){ const p=state.playlists.find(p=>p.id===state.selected); let tracks=p ? state.tracks.filter(t=>playlistTrackKeys(p).includes(t.key)) : [...state.tracks]; const query=state.query.trim().toLowerCase(); if(query)tracks=tracks.filter(t=>[t.title,t.artist,t.album].some(value=>(value||'').toLowerCase().includes(query))); if(state.sort.key){const {key,direction}=state.sort;tracks.sort((a,b)=>{const one=key==='duration'?(a[key]||0):(a[key]||'').toLowerCase(),two=key==='duration'?(b[key]||0):(b[key]||'').toLowerCase();return (one>two?1:one<two?-1:0)*(direction==='asc'?1:-1)});} return tracks; }
function selectedPlaylist(){ return state.playlists.find(p=>p.id===state.selected); }

function render(){ const tracks=visibleTracks(), playlist=selectedPlaylist(); $('#track-count').textContent=state.tracks.length; const canRefresh=Boolean(window.electronAPI&&state.libraryFolders.length);$('#refresh-folders').disabled=!canRefresh;$('#manage-folders').disabled=!canRefresh; $('.nav-item').classList.toggle('active',state.selected==='all'); $('#view-title').textContent=playlist?.name || 'All music'; $('#view-kicker').textContent=playlist ? 'PLAYLIST' : 'LIBRARY'; $('#view-subtitle').textContent=tracks.length ? `${tracks.length} ${tracks.length===1?'track':'tracks'}${state.query?' matching filter':''} · saved to this device` : state.query ? 'No songs match this filter.' : playlist ? 'No tracks in this playlist yet.' : 'Your saved collection will appear here.'; $('#play-all').style.visibility=tracks.length?'visible':'hidden'; $('#sync-playlist').hidden=!playlist||!tracks.length; $('#show-playing').disabled=!state.currentId;
 $('#playlist-list').innerHTML=state.playlists.map(p=>`<div class="playlist-item ${p.id===state.selected?'selected':''}" data-playlist-row="${p.id}" draggable="true" title="Drag to reorder this playlist"><button class="playlist-select" data-playlist="${p.id}"${p.id===state.selected?' aria-current="page"':''}><span>☷</span><span>${escapeHTML(p.name)}</span></button><span class="playlist-actions"><button data-rename="${p.id}" aria-label="Rename ${escapeHTML(p.name)}">✎</button><button data-delete="${p.id}" aria-label="Delete ${escapeHTML(p.name)}">×</button></span></div>`).join('');
 $('#empty-state').hidden=tracks.length>0; $('#track-area').hidden=!tracks.length;
 document.querySelectorAll('[data-sort]').forEach(button=>{const active=button.dataset.sort===state.sort.key;button.classList.toggle('sorted',active);button.querySelector('i').textContent=active?(state.sort.direction==='asc'?'↑':'↓'):''});
 $('#track-list').innerHTML=tracks.map(t=>`<div class="track-row ${t.id===state.currentId?'playing':''} ${state.selectedTrackIds.has(t.id)?'selected-track':''}" data-track="${t.id}" draggable="true" title="Click to select · Ctrl/Cmd-click for multiple · Shift-click for a range · Drag to add to a playlist"><div class="title-cell"><div class="mini-art">${t.id===state.currentId?'▶':'♫'}</div><span class="track-title" data-edit="title">${escapeHTML(t.title)}</span></div><span class="artist-cell" data-edit="artist">${escapeHTML(t.artist || 'Unknown artist')}</span><span class="album-cell" data-edit="album">${escapeHTML(t.album || '—')}</span><span class="time-cell">${time(t.duration)}</span><span class="track-actions">${t.path&&window.electronAPI?`<button class="external-drag" draggable="true" data-external-drag="${t.id}" title="Drag this audio file to another app or your desktop" aria-label="Drag ${escapeHTML(t.title)} to another app">↗</button>`:''}<button class="row-menu" title="Song options" data-menu="${t.id}">•••</button></span></div>`).join('');
}
function escapeHTML(s){const el=document.createElement('span');el.textContent=s;return el.innerHTML}
async function addTrack(file){ const key=`${file.name}-${file.size}-${file.lastModified}`,metadata=await trackMetadata(file); const existing=state.tracks.find(t=>t.key===key); if(existing){Object.assign(existing,metadata,{file,handle:null});await put('tracks',existing);return} const temp=URL.createObjectURL(file), probe=new Audio(temp); const duration=await new Promise(resolve=>{probe.onloadedmetadata=()=>resolve(probe.duration);probe.onerror=()=>resolve(0)}); URL.revokeObjectURL(temp); const track={id:id(),key,...metadata,duration,handle:null,file}; await put('tracks',track);state.tracks.push(track); }
async function addNativeTracks(tracks,showToast=true){let added=0;for(const native of tracks){const existing=state.tracks.find(track=>track.key===native.key);if(existing){Object.assign(existing,native,{file:null,handle:null});await put('tracks',existing)}else{const track={id:id(),...native,file:null,handle:null};await put('tracks',track);state.tracks.push(track);added++}}render();if(showToast)toast(`${added||tracks.length} file${(added||tracks.length)===1?'':'s'} loaded from folder`);return added}
function saveLibraryFolders(){localStorage.setItem('nightwave-library-folders',JSON.stringify(state.libraryFolders))}
async function loadFolder(){if(window.electronAPI){const result=await window.electronAPI.pickMusicFolder();if(!result)return;if(!state.libraryFolders.includes(result.directory)){state.libraryFolders.push(result.directory);saveLibraryFolders()}if(result.tracks.length)await addNativeTracks(result.tracks);else{render();toast('No music files found in that folder. It will be checked when you refresh.')}return}const picker=$('#folder-input');if('webkitdirectory' in picker){picker.click()}else{$('#file-input').click();toast('Your browser does not support folder selection. Select your music files instead.')} }
async function refreshLoadedFolders(){if(!state.libraryFolders.length||!window.electronAPI)return;const button=$('#refresh-folders');button.disabled=true;button.textContent='↻ Refreshing…';try{const result=await window.electronAPI.refreshMusicFolders(state.libraryFolders),added=await addNativeTracks(result.tracks,false),unavailable=result.unavailableFolders.length;toast(`${added?`${added} new file${added===1?'':'s'} found`:'Folders are up to date'}${unavailable?` · ${unavailable} folder${unavailable===1?'':'s'} unavailable`:''}.`)}catch(error){toast(error.message||'Could not refresh the music folders.')}finally{button.textContent='↻ Refresh folders';render()}}
function manageLibraryFolders(){if(!state.libraryFolders.length)return;const dialog=document.createElement('dialog');dialog.className='text-dialog folder-dialog';dialog.innerHTML='<form method="dialog"><p>Refresh will scan the folders listed here. Removing a folder does not remove music already loaded in Nightwave.</p><ul class="folder-list"></ul><div><button class="dialog-primary" value="done">Done</button></div></form>';const list=dialog.querySelector('.folder-list'),paint=()=>{list.innerHTML=state.libraryFolders.map((folder,index)=>`<li><code>${escapeHTML(folder)}</code><button type="button" data-remove-folder="${index}" aria-label="Remove ${escapeHTML(folder)}">Remove</button></li>`).join('')};paint();dialog.onclick=event=>{const button=event.target.closest('[data-remove-folder]');if(!button)return;state.libraryFolders.splice(Number(button.dataset.removeFolder),1);saveLibraryFolders();render();paint()};dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal()}
async function addFiles(files){for(const file of files)await addTrack(file);render();toast(`${files.length} file${files.length===1?'':'s'} saved to your library`)}
async function clearLibrary(){ if(!state.tracks.length){toast('Your library is already empty.');return}document.querySelector('.library-tools[open]')?.removeAttribute('open');if(!await askConfirm(`Unload all ${state.tracks.length} saved music file${state.tracks.length===1?'':'s'}? Your playlists will keep their song assignments when you load these files again.`,'Continue'))return;if(!await askConfirm('Final confirmation: this will remove every loaded track from Nightwave. Your source files and playlist assignments will remain unchanged.','Unload all music'))return; audio.pause();audio.removeAttribute('src');audio.load();if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.objectUrl=null;state.currentId=null;await Promise.all(state.tracks.map(track=>del('tracks',track.id)));state.tracks=[];$('#now-title').textContent='Nothing playing';$('#now-artist').textContent='Choose a track from your library';$('#play').textContent='▶';render();toast('Library cleared. Playlist assignments were kept.');}
async function removeSelectedTracks(){const ids=[...state.selectedTrackIds];if(!ids.length)return;const playlist=selectedPlaylist(),count=ids.length;if(playlist){if(!await askConfirm(`Remove ${count} selected track${count===1?'':'s'} from “${playlist.name}”? The audio files remain in All Music.`,'Remove tracks'))return;const keys=new Set(state.tracks.filter(track=>ids.includes(track.id)).map(track=>track.key));playlist.trackKeys=playlistTrackKeys(playlist).filter(trackKey=>!keys.has(trackKey));await put('playlists',playlist);state.selectedTrackIds=new Set();state.selectionAnchor=null;render();toast(`${count} track${count===1?'':'s'} removed from ${playlist.name}.`);return}if(!await askConfirm(`Unload ${count} selected track${count===1?'':'s'} from Nightwave? The source audio files will not be deleted, and their playlist assignments will be kept.`,'Unload tracks'))return;if(ids.includes(state.currentId)){audio.pause();audio.removeAttribute('src');audio.load();state.currentId=null;$('#now-title').textContent='Nothing playing';$('#now-artist').textContent='Choose a track from your library';$('#play').textContent='▶'}await Promise.all(ids.map(trackId=>del('tracks',trackId)));state.tracks=state.tracks.filter(track=>!ids.includes(track.id));state.selectedTrackIds=new Set();state.selectionAnchor=null;render();toast(`${count} track${count===1?'':'s'} unloaded. Playlist assignments were kept.`)}
async function playTrack(trackId){ const track=state.tracks.find(t=>t.id===trackId);if(!track)return; try { if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.objectUrl=null;audio.src=track.path&&window.electronAPI?await window.electronAPI.fileUrl(track.path):URL.createObjectURL(track.file);if(!audio.src)throw Error('File unavailable');state.currentId=track.id;await audio.play();$('#now-title').textContent=track.title;$('#now-artist').textContent=track.artist;$('#play').textContent='Ⅱ';render(); }catch(e){toast('This file is no longer available. Load its folder again.');} }
function nextTrack(back=false){let tracks=visibleTracks();if(!tracks.length)return;let ix=tracks.findIndex(t=>t.id===state.currentId);if(state.shuffle)ix=Math.floor(Math.random()*tracks.length);else ix=(ix+(back?-1:1)+tracks.length)%tracks.length;playTrack(tracks[ix].id)}
async function newPlaylist(){ const name=await askText('Name your playlist');if(!name)return; const p={id:id(),name,trackKeys:[],order:state.playlists.length};await put('playlists',p);state.playlists.push(p);state.selected=p.id;render(); }
async function renamePlaylist(playlistId){const playlist=state.playlists.find(p=>p.id===playlistId);if(!playlist)return;const name=await askText('Rename playlist',playlist.name);if(!name||name===playlist.name)return;playlist.name=name;await put('playlists',playlist);render();}
async function deletePlaylist(playlistId){const playlist=state.playlists.find(p=>p.id===playlistId);if(!playlist||!await askConfirm(`Delete the playlist “${playlist.name}”? Its music files will stay in your library.`,'Delete playlist'))return;await del('playlists',playlistId);state.playlists=state.playlists.filter(p=>p.id!==playlistId);if(state.selected===playlistId)state.selected='all';render();toast('Playlist deleted.');}
async function songMenu(trackId,anchor){const track=state.tracks.find(item=>item.id===trackId);if(!track)return;const choice=await askSongAction(anchor);if(choice==='playlist')return addToPlaylist(trackId);if(choice==='reveal'){if(track.path&&window.electronAPI)await window.electronAPI.showInFolder(track.path);else toast('This file must be loaded through the Electron folder picker first.')}}
async function editMetadata(trackId,field){const track=state.tracks.find(item=>item.id===trackId);if(!track)return;if(!window.electronAPI||!track.path){toast('Metadata editing is available for files loaded through the Electron folder picker.');return}const label={title:'Title',artist:'Artist',album:'Album'}[field],value=await askText(`Edit ${label}`,track[field]||'');if(value===null||value===track[field])return;if(!await askConfirm(`Write this ${label.toLowerCase()} change to the source MP3 file?`,'Write tag'))return;try{const updated=await window.electronAPI.writeTags({filePath:track.path,title:field==='title'?value:track.title,artist:field==='artist'?value:track.artist,album:field==='album'?value:track.album});Object.assign(track,updated);await put('tracks',track);render();toast(`${label} updated.`)}catch(error){toast(error.message)}}
async function addToPlaylist(trackId){const track=state.tracks.find(item=>item.id===trackId);if(!track)return;if(!state.playlists.length){await newPlaylist();if(!state.playlists.length)return} const name=await askText(`Add to playlist (${state.playlists.map((p,i)=>`${i+1}: ${p.name}`).join(' · ')})`);const p=state.playlists.find(p=>p.name.toLowerCase()===name?.toLowerCase())||state.playlists[Number(name)-1];if(!p){if(name)toast('Playlist not found.');return}if(!playlistTrackKeys(p).includes(track.key)){p.trackKeys=[...playlistTrackKeys(p),track.key];await put('playlists',p);toast('Added to '+p.name)}}
function toast(message){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function askText(label,initial=''){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='text-dialog';dialog.innerHTML=`<form method="dialog"><label>${escapeHTML(label)}<input autofocus value="${escapeHTML(initial)}" /></label><div><button type="button" data-cancel>Cancel</button><button class="dialog-primary" value="confirm">Save</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close('cancel');dialog.addEventListener('close',()=>{const value=dialog.returnValue==='confirm'?dialog.querySelector('input').value.trim():null;dialog.remove();resolve(value)});dialog.showModal();dialog.querySelector('input').select()})}
function askConfirm(message,action='Confirm'){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='text-dialog';dialog.innerHTML=`<form method="dialog"><p>${escapeHTML(message)}</p><div><button type="button" data-cancel>Cancel</button><button class="dialog-primary" value="confirm">${escapeHTML(action)}</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close('cancel');dialog.addEventListener('close',()=>{const accepted=dialog.returnValue==='confirm';dialog.remove();resolve(accepted)});dialog.showModal()})}
function askSongAction(anchor){return new Promise(resolve=>{const menu=document.createElement('div'),rect=anchor.getBoundingClientRect();menu.className='song-popover';menu.innerHTML='<button data-action="playlist">Add to playlist</button><button data-action="reveal">Show in file manager</button>';document.body.append(menu);const width=menu.offsetWidth,height=menu.offsetHeight;menu.style.left=`${Math.max(10,Math.min(window.innerWidth-width-10,rect.right-width))}px`;menu.style.top=`${Math.max(10,Math.min(window.innerHeight-height-10,rect.bottom+6))}px`;const close=action=>{menu.remove();document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',escape);resolve(action)};const outside=event=>{if(!menu.contains(event.target)&&event.target!==anchor)close('cancel')};const escape=event=>{if(event.key==='Escape')close('cancel')};menu.onclick=event=>{const button=event.target.closest('[data-action]');if(button)close(button.dataset.action)};setTimeout(()=>{document.addEventListener('mousedown',outside);document.addEventListener('keydown',escape)},0)})}
function paintSelection(){document.querySelectorAll('#track-list [data-track]').forEach(row=>row.classList.toggle('selected-track',state.selectedTrackIds.has(row.dataset.track)))}
function selectTracks(trackId,event){const tracks=visibleTracks(),ids=tracks.map(track=>track.id);if(event.shiftKey&&state.selectionAnchor){const start=ids.indexOf(state.selectionAnchor),end=ids.indexOf(trackId);if(start>=0&&end>=0)state.selectedTrackIds=new Set(ids.slice(Math.min(start,end),Math.max(start,end)+1));}else if(event.ctrlKey||event.metaKey){if(state.selectedTrackIds.has(trackId))state.selectedTrackIds.delete(trackId);else state.selectedTrackIds.add(trackId);state.selectedTrackIds=new Set(state.selectedTrackIds);state.selectionAnchor=trackId;}else{state.selectedTrackIds=new Set([trackId]);state.selectionAnchor=trackId;}paintSelection();}
function showPlayingTrack(){if(!state.currentId){toast('Nothing is playing.');return}const track=state.tracks.find(item=>item.id===state.currentId),playlist=selectedPlaylist();if(!track){toast('The playing track is no longer in your library.');return}if(playlist&&!playlistTrackKeys(playlist).includes(track.key))state.selected='all';state.query='';$('#search').value='';state.selectedTrackIds=new Set([state.currentId]);state.selectionAnchor=state.currentId;render();requestAnimationFrame(()=>document.querySelector(`#track-list [data-track="${state.currentId}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}));}
function showSyncProgress(total){const panel=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('span'),bar=document.createElement('progress');panel.className='sync-progress';panel.setAttribute('role','status');panel.setAttribute('aria-live','polite');title.textContent='Syncing to phone';detail.textContent=`Preparing ${total} track${total===1?'':'s'}…`;bar.max=total;bar.value=0;panel.append(title,detail,bar);document.body.append(panel);return {update:({completed,fileName})=>{bar.value=completed;detail.textContent=`${completed+1} of ${total} · ${fileName}`},remove:()=>panel.remove()}}
async function syncPlaylistToPhone(){const playlist=selectedPlaylist();if(!playlist)return;const tracks=state.tracks.filter(track=>playlistTrackKeys(playlist).includes(track.key)&&track.path);if(!tracks.length){toast('This playlist has no tracks available to sync. Load its music from a folder first.');return}if(!await askConfirm(`Copy ${tracks.length} track${tracks.length===1?'':'s'} from “${playlist.name}” to a matching folder in your phone’s Music directory? Existing files with the same name will be skipped.`,'Sync to phone'))return;const button=$('#sync-playlist'),progress=showSyncProgress(tracks.length);button.disabled=true;button.querySelector('span').textContent='Syncing…';try{const result=await window.electronAPI.syncToPhone({filePaths:tracks.map(track=>track.path),playlistName:playlist.name},progress.update);const summary=`${result.copied} copied${result.skipped?`, ${result.skipped} already on phone`:''}${result.failed.length?`, ${result.failed.length} failed`:''}.`;toast(summary);if(result.failed.length)console.warn('Phone sync failures:',result.failed)}catch(error){toast(error.message||'Could not sync to the phone.')}finally{progress.remove();button.disabled=false;button.querySelector('span').textContent='Sync to phone'}}

$('#load-folder').onclick=$('#empty-load').onclick=loadFolder; $('#add-files').onclick=()=>$('#file-input').click();$('#clear-library').onclick=clearLibrary;$('#show-playing').onclick=showPlayingTrack;$('#sync-playlist').onclick=syncPlaylistToPhone;$('#file-input').onchange=async e=>{await addFiles(e.target.files);e.target.value=''};$('#folder-input').onchange=async e=>{await addFiles(e.target.files);e.target.value=''};$('#new-playlist').onclick=newPlaylist;
$('#refresh-folders').onclick=refreshLoadedFolders;$('#manage-folders').onclick=manageLibraryFolders;
const setMaximizeButton=maximized=>{const button=$('#window-maximize');button.textContent=maximized?'❐':'□';button.title=maximized?'Restore':'Maximize';button.setAttribute('aria-label',button.title+' window')};$('#window-minimize').onclick=()=>window.electronAPI?.minimizeWindow();$('#window-maximize').onclick=async()=>setMaximizeButton(await window.electronAPI?.toggleMaximizeWindow());$('#window-close').onclick=()=>window.electronAPI?.closeWindow();window.electronAPI?.onWindowMaximized(setMaximizeButton);
$('#sidebar-resizer').onpointerdown=e=>{e.preventDefault();const resizer=e.currentTarget;resizer.setPointerCapture(e.pointerId);document.body.classList.add('resizing-sidebar');const resize=event=>{const width=Math.max(sidebarMin,Math.min(sidebarMax,event.clientX));document.documentElement.style.setProperty('--sidebar-width',`${width}px`);localStorage.setItem('nightwave-sidebar-width',width)};const stop=event=>{document.body.classList.remove('resizing-sidebar');resizer.releasePointerCapture(event.pointerId);resizer.removeEventListener('pointermove',resize);resizer.removeEventListener('pointerup',stop);resizer.removeEventListener('pointercancel',stop)};resizer.addEventListener('pointermove',resize);resizer.addEventListener('pointerup',stop);resizer.addEventListener('pointercancel',stop)};
$('#playlist-list').onclick=async e=>{const rename=e.target.closest('[data-rename]');if(rename){await renamePlaylist(rename.dataset.rename);return}const remove=e.target.closest('[data-delete]');if(remove){await deletePlaylist(remove.dataset.delete);return}const b=e.target.closest('[data-playlist]');if(b){state.selected=b.dataset.playlist;state.selectedTrackIds=new Set();state.selectionAnchor=null;render()}};
$('#track-list').onclick=e=>{if(e.target.closest('[data-external-drag]'))return;const menu=e.target.closest('[data-menu]');if(menu){songMenu(menu.dataset.menu,menu);return}const row=e.target.closest('[data-track]');if(row)selectTracks(row.dataset.track,e)};
$('#track-list').ondblclick=e=>{const row=e.target.closest('[data-track]');if(!row)return;const editable=e.target.closest('[data-edit]');if(editable){editMetadata(row.dataset.track,editable.dataset.edit);return}playTrack(row.dataset.track)};
$('#track-list').ondragstart=e=>{const external=e.target.closest('[data-external-drag]');if(external){const track=state.tracks.find(item=>item.id===external.dataset.externalDrag);if(track?.path&&window.electronAPI){e.preventDefault();window.electronAPI.startExternalDrag(track.path)}return}const row=e.target.closest('[data-track]');if(!row)return;const ids=state.selectedTrackIds.has(row.dataset.track)?[...state.selectedTrackIds]:[row.dataset.track];if(!state.selectedTrackIds.has(row.dataset.track)){state.selectedTrackIds=new Set(ids);state.selectionAnchor=row.dataset.track;paintSelection()}e.dataTransfer.setData('text/plain',JSON.stringify(ids));e.dataTransfer.effectAllowed='copy';row.classList.add('dragging')};
$('#track-list').ondragend=e=>{e.target.closest('[data-track]')?.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'))};
$('#playlist-list').ondragstart=e=>{const row=e.target.closest('[data-playlist-row]');if(!row||e.target.closest('.playlist-actions'))return;e.dataTransfer.setData('application/x-nightwave-playlist',row.dataset.playlistRow);e.dataTransfer.effectAllowed='move';row.classList.add('dragging')};
$('#playlist-list').ondragend=e=>{e.target.closest('[data-playlist-row]')?.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'))};
$('#playlist-list').ondragover=e=>{const row=e.target.closest('[data-playlist-row]');if(!row)return;e.preventDefault();const reordering=Array.from(e.dataTransfer.types).includes('application/x-nightwave-playlist');e.dataTransfer.dropEffect=reordering?'move':'copy';document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));row.classList.add('drop-target')};
$('#playlist-list').ondragleave=e=>{if(!e.currentTarget.contains(e.relatedTarget))document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'))};
$('#playlist-list').ondrop=async e=>{e.preventDefault();const row=e.target.closest('[data-playlist-row]'),sourceId=e.dataTransfer.getData('application/x-nightwave-playlist');document.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));if(!row)return;if(sourceId){const from=state.playlists.findIndex(playlist=>playlist.id===sourceId),to=state.playlists.findIndex(playlist=>playlist.id===row.dataset.playlistRow);if(from<0||to<0||from===to)return;const [playlist]=state.playlists.splice(from,1);state.playlists.splice(to,0,playlist);await Promise.all(state.playlists.map((item,index)=>{item.order=index;return put('playlists',item)}));render();toast('Playlist order saved.');return}let trackIds=[];try{trackIds=JSON.parse(e.dataTransfer.getData('text/plain'))}catch{trackIds=[e.dataTransfer.getData('text/plain')]}if(!trackIds.length)return;const playlist=state.playlists.find(p=>p.id===row.dataset.playlistRow);if(!playlist)return;const keys=state.tracks.filter(track=>trackIds.includes(track.id)).map(track=>track.key),added=keys.filter(trackKey=>!playlistTrackKeys(playlist).includes(trackKey));if(!added.length){toast('Those tracks are already in this playlist.');return}playlist.trackKeys=[...playlistTrackKeys(playlist),...added];await put('playlists',playlist);toast(`${added.length} track${added.length===1?'':'s'} added to ${playlist.name}`)};
$('.track-header').onclick=e=>{const button=e.target.closest('[data-sort]');if(!button)return;const key=button.dataset.sort;state.sort={key,direction:state.sort.key===key&&state.sort.direction==='asc'?'desc':'asc'};render()};
$('#search').oninput=e=>{state.query=e.target.value;render()};
$('.nav-item').onclick=()=>{state.selected='all';state.selectedTrackIds=new Set();state.selectionAnchor=null;render()};$('#play-all').onclick=()=>{const t=visibleTracks()[0];if(t)playTrack(t.id)};
document.addEventListener('keydown',e=>{const target=e.target;if(e.key!=='Delete'||target.matches('input,textarea,[contenteditable]')||document.querySelector('dialog[open]'))return;if(!state.selectedTrackIds.size)return;e.preventDefault();removeSelectedTracks()});
$('#play').onclick=()=>{if(!state.currentId){const t=visibleTracks()[0];if(t)playTrack(t.id)}else if(audio.paused){audio.play();$('#play').textContent='Ⅱ'}else{audio.pause();$('#play').textContent='▶'}};$('#next').onclick=()=>nextTrack();$('#previous').onclick=()=>nextTrack(true);$('#shuffle').onclick=e=>{state.shuffle=!state.shuffle;e.currentTarget.classList.toggle('active',state.shuffle)};$('#repeat').onclick=e=>{state.repeat=!state.repeat;e.currentTarget.classList.toggle('active',state.repeat)};
audio.ontimeupdate=()=>{const value=audio.duration?audio.currentTime/audio.duration*100:0;$('#progress').value=value;$('#progress').style.setProperty('--value',value+'%');$('#current-time').textContent=time(audio.currentTime)};audio.onloadedmetadata=()=>{$('#duration').textContent=time(audio.duration)};audio.onended=()=>state.repeat?(audio.currentTime=0,audio.play()):nextTrack();$('#progress').oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*(e.target.value/100)};const savedVolumeValue=localStorage.getItem('nightwave-volume'),savedVolume=Number(savedVolumeValue),initialVolume=savedVolumeValue!==null&&Number.isFinite(savedVolume)&&savedVolume>=0&&savedVolume<=1?savedVolume:.8,volumeControl=$('#volume');audio.volume=initialVolume;volumeControl.value=initialVolume;volumeControl.style.setProperty('--value',`${initialVolume*100}%`);volumeControl.oninput=e=>{audio.volume=e.target.value;volumeControl.style.setProperty('--value',`${audio.volume*100}%`);localStorage.setItem('nightwave-volume',audio.volume)};
const looksTemporaryTitle = value => /^(?:video[_ -]?download|download[_ -]?(?:temp|video)?|temp(?:orary)?|unknown|untitled)[_ -]*/i.test(String(value||'').trim());
async function refreshSavedMetadata(){ const updates=state.tracks.filter(track=>track.file).map(async track=>{const metadata=await trackMetadata(track.file);if(track.title!==metadata.title||track.artist!==metadata.artist||track.album!==metadata.album){Object.assign(track,metadata);await put('tracks',track)}});await Promise.all(updates);if(window.electronAPI){for(const track of state.tracks.filter(item=>item.path&&looksTemporaryTitle(item.title))){try{const metadata=await window.electronAPI.readTrack(track.path);Object.assign(track,metadata);await put('tracks',track)}catch{}}}render(); }
async function migratePlaylists(){const keyForId=new Map(state.tracks.map(track=>[track.id,track.key]));let changed=false;state.playlists.sort((a,b)=>(a.order??Number.MAX_SAFE_INTEGER)-(b.order??Number.MAX_SAFE_INTEGER));for(const [index,playlist] of state.playlists.entries()){if(!Array.isArray(playlist.trackKeys)){playlist.trackKeys=(playlist.trackIds||[]).map(trackId=>keyForId.get(trackId)).filter(Boolean);delete playlist.trackIds;changed=true}if(playlist.order!==index){playlist.order=index;changed=true}}if(changed)await Promise.all(state.playlists.map(playlist=>put('playlists',playlist)))}
(async()=>{db=await openDB();state.tracks=await all('tracks');state.playlists=await all('playlists');await migratePlaylists();render();const legacyCount=state.tracks.filter(track=>!track.file&&!track.path).length;if(legacyCount)toast(`${legacyCount} older ${legacyCount===1?'track needs':'tracks need'} to be loaded again to read their tags.`);refreshSavedMetadata()})().catch(()=>toast('Storage could not be opened.'));
