const { app, BrowserWindow, dialog, ipcMain, shell } = require('electron');
const path = require('node:path');
const fs = require('node:fs/promises');
const { pathToFileURL } = require('node:url');
const { spawn } = require('node:child_process');
const NodeID3 = require('node-id3');

const AUDIO_EXTENSIONS = new Set(['.mp3', '.m4a', '.wav', '.ogg', '.flac', '.aac', '.opus']);
const KIO_PHONE_MUSIC_URI = 'mtp:/Redmi Note 11/Internal shared storage/Music/';
const isTemporaryTag = value => /^(?:video[_ -]?download|download[_ -]?(?:temp|video)?|temp(?:orary)?|unknown|untitled)[_ -]*/i.test(String(value || '').trim());
function preferredTag(metadata, commonValue, ids) { if (!isTemporaryTag(commonValue)) return commonValue; for (const tags of Object.values(metadata.native)) { const tag = tags.find(item => ids.includes(item.id) && item.value && !isTemporaryTag(item.value)); if (tag) return String(tag.value); } return commonValue; }
function createWindow() { const window = new BrowserWindow({ width: 1800, height: 980, minWidth: 900, minHeight: 620, backgroundColor: '#0d0d0f', icon: path.join(__dirname, 'assets', 'nightwave-icon.png'), webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false } }); window.loadFile('index.html'); }
function runCommand(command,args) { return new Promise((resolve, reject) => { const child=spawn(command,args), output=[]; child.stdout.on('data',chunk=>output.push(chunk)); child.stderr.on('data',chunk=>output.push(chunk)); child.on('error',reject); child.on('close',code=>code===0?resolve(Buffer.concat(output).toString()):reject(new Error(Buffer.concat(output).toString().trim()||`${command} exited with code ${code}`))); }); }
const runGio = args => runCommand('gio',args);
const playlistFolder = playlistName => encodeURIComponent(playlistName);
const kioPlaylistUri = playlistName => `${KIO_PHONE_MUSIC_URI}${playlistFolder(playlistName)}`;
const kioPlaylistDirectoryUri = playlistName => `${kioPlaylistUri(playlistName)}/`;
const kioFileUri = (filePath,playlistName) => `${kioPlaylistDirectoryUri(playlistName)}${encodeURIComponent(path.basename(filePath))}`;
async function phoneMusicUri(playlistName) { const mounts=await runGio(['mount','-li']); const roots=[...mounts.matchAll(/mtp:\/\/[^\s]+/g)].map(match=>match[0]); if(!roots.length)throw new Error('No MTP phone is mounted. Unlock your phone, choose File transfer, then try again.'); const root=roots.find(uri=>mounts.slice(Math.max(0,mounts.indexOf(uri)-300),mounts.indexOf(uri)+300).includes('Redmi Note 11'))||roots[0]; return `${root.replace(/\/?$/,'/')}Internal%20shared%20storage/Music/${playlistFolder(playlistName)}/`; }
async function syncWithGio(filePaths,musicUri,onProgress) { await runGio(['mkdir','-p',musicUri]); let copied=0,skipped=0;const failed=[]; for(const [index,filePath] of filePaths.entries()){onProgress(index,filePath);const destination=`${musicUri}${encodeURIComponent(path.basename(filePath))}`;try{await runGio(['info',destination]);skipped++;continue}catch{}try{await runGio(['copy','--no-target-directory',filePath,destination]);copied++}catch(error){failed.push(`${path.basename(filePath)}: ${error.message}`)}}return {copied,skipped,failed}; }
async function syncWithKio(filePaths,playlistName,onProgress) { const options=['--platform','offscreen','--noninteractive'],folder=kioPlaylistUri(playlistName),target=kioPlaylistDirectoryUri(playlistName);try{await runCommand('kioclient5',[...options,'stat',folder])}catch{await runCommand('kioclient5',[...options,'mkdir',folder])}let copied=0,skipped=0;const failed=[]; for(const [index,filePath] of filePaths.entries()){onProgress(index,filePath);const destination=kioFileUri(filePath,playlistName);try{await runCommand('kioclient5',[...options,'stat',destination]);skipped++;continue}catch{}try{await runCommand('kioclient5',[...options,'copy',filePath,target]);copied++}catch(error){failed.push(`${path.basename(filePath)}: ${error.message}`)}}if(!copied&&failed.length===filePaths.length)throw new Error(`KDE could not access the connected phone at ${target}. ${failed[0]}`);return {copied,skipped,failed}; }
async function musicFiles(directory) { const entries = await fs.readdir(directory, { withFileTypes: true }); const nested = await Promise.all(entries.map(async entry => { const target = path.join(directory, entry.name); if (entry.isDirectory()) return musicFiles(target); return AUDIO_EXTENSIONS.has(path.extname(entry.name).toLowerCase()) ? [target] : []; })); return nested.flat(); }
async function readTrack(filePath) { const fallback = path.basename(filePath, path.extname(filePath)); try { const { parseFile } = await import('music-metadata'); const metadata = await parseFile(filePath, { duration: true, skipCovers: true }); return { path: filePath, key: filePath, title: preferredTag(metadata, metadata.common.title, ['TIT2', 'TT2', 'title']) || fallback, artist: preferredTag(metadata, metadata.common.artist, ['TPE1', 'TP1', 'artist']) || 'Unknown artist', album: preferredTag(metadata, metadata.common.album, ['TALB', 'TAL', 'album']) || 'Local files', duration: metadata.format.duration || 0 }; } catch { return { path: filePath, key: filePath, title: fallback, artist: 'Unknown artist', album: 'Local files', duration: 0 }; } }
app.whenReady().then(() => { createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
ipcMain.handle('music:pick-folder', async () => { const result = await dialog.showOpenDialog({ properties: ['openDirectory'] }); if (result.canceled) return []; const files = await musicFiles(result.filePaths[0]); return Promise.all(files.map(readTrack)); });
ipcMain.handle('music:read-track', (_event, filePath) => readTrack(filePath));
ipcMain.handle('music:show-in-folder', (_event, filePath) => { shell.showItemInFolder(filePath); });
ipcMain.handle('music:file-url', (_event, filePath) => pathToFileURL(filePath).href);
ipcMain.handle('music:sync-to-phone', async (event, request) => { const filePaths=request?.filePaths,playlistName=String(request?.playlistName||'Nightwave').trim()||'Nightwave';if(!Array.isArray(filePaths)||!filePaths.length)throw new Error('There are no local music files to sync.');const onProgress=(completed,filePath)=>event.sender.send('music:sync-progress',{completed,total:filePaths.length,fileName:path.basename(filePath)});try{return await syncWithGio(filePaths,await phoneMusicUri(playlistName),onProgress)}catch(error){if(!String(error.message).includes('No MTP phone is mounted'))throw error;return syncWithKio(filePaths,playlistName,onProgress)} });
ipcMain.handle('music:write-tags', async (_event, { filePath, title, artist, album }) => { if (path.extname(filePath).toLowerCase() !== '.mp3') throw new Error('Editing tags is currently supported for MP3 files only.'); const ok = NodeID3.update({ title, artist, album }, filePath); if (!ok) throw new Error('Could not write tags to this file.'); return readTrack(filePath); });
